added Analog Outputs
ros-drivers/phidgets_drivers pull request #103
Opened 2021-09-28 12:50 UTC by CaPlasberg

corresponding issue #102

2021-09-28 13:24 UTC, clalancette requested changes
Thanks for the contribution!  I've left a number of things to fix.  You should also consider running `python3 clang-check-style.py` over these files to make sure that the style checker is happy.

2021-09-28 13:24 UTC, clalancette commented on phidgets_analog_outputs/CHANGELOG.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Don't add this CHANGELOG; it will get automatically generated when we do a release.

2021-09-28 13:24 UTC, clalancette commented on phidgets_analog_outputs/package.xml
> +  <author>Chris Lalancette</author>
You should change this to yourself, since you made this one :).

2021-09-28 13:24 UTC, clalancette commented on phidgets_analog_outputs/README.md
> +Phidgets digital inputs ROS driver
```suggestion
Phidgets analog outputs ROS driver
```

(the same goes for everything below)

2021-09-28 13:24 UTC, clalancette commented on phidgets_api/include/phidgets_api/analog_outputs.h
> +//#include <functional>
Remove this dead line of code.

2021-09-28 13:24 UTC, clalancette commented on phidgets_api/src/analog_output.cpp
> +//#include <memory>
Remove these dead lines of code.

2021-09-28 13:24 UTC, clalancette commented on phidgets_api/src/analog_output.cpp
> +                         bool is_hub_port_device, int channel)
This looks like there are probably tabs in this line; line it up with the above, and make sure to use spaces.

2021-09-28 13:24 UTC, clalancette commented on phidgets_api/include/phidgets_api/analog_output.h
> +#include <functional>
It doesn't look like this header is used, so just remove it.

2021-09-28 13:24 UTC, clalancette commented on phidgets_api/src/analog_outputs.cpp
> +#include <string>
I think the only one of these that is needed in this file is `memory`; remove the rest.

2021-09-28 13:24 UTC, clalancette commented on phidgets_msgs/srv/SetAnalogOutput.srv
> +float32 voltage
The API call above and in the libphidget22 library take in a double, so I'll suggest switching this to a `float64` instead.

2021-09-28 13:24 UTC, clalancette commented on phidgets_analog_outputs/src/phidgets_analog_outputs_nodelet.cpp
> +    dos_ = std::make_unique<AnalogOutputsRosI>(nh, nh_private);
```suggestion
    aos_ = std::make_unique<AnalogOutputsRosI>(nh, nh_private);
```

2021-09-28 13:24 UTC, clalancette commented on phidgets_analog_outputs/launch/analog_outputs.launch
> +<!-- Phidgets Digital Outputs launch file -->
```suggestion
<!-- Phidgets Analog Outputs launch file -->
```

2021-09-28 13:24 UTC, clalancette commented on phidgets_analog_outputs/include/phidgets_analog_outputs/phidgets_analog_outputs_nodelet.h
> +    std::unique_ptr<AnalogOutputsRosI> dos_;
```suggestion
    std::unique_ptr<AnalogOutputsRosI> aos_;
```

2021-09-28 13:24 UTC, clalancette commented on phidgets_analog_outputs/src/analog_outputs_ros_i.cpp
> +                                         const std::string& topicname)
This is not lined up properly; it looks like is is probably using tabs instead of spaces.  Please use spaces everywhere.

2021-09-28 13:24 UTC, clalancette commented on phidgets_analog_outputs/src/analog_outputs_ros_i.cpp
> +void AnalogOutputSetter::setMsgCallback(const std_msgs::Float32::ConstPtr& msg)
See my comment about the type of this; I think this should probably be a `Float64`.

2021-09-28 14:22 UTC, clalancette requested changes
Just a few more minor changes to make, then I'm happy with it.  @mintar any thoughts on this?

2021-09-28 14:22 UTC, clalancette commented on phidgets_analog_outputs/README.md
> +* `/set_analogl_output` (`phidgets_msgs/SetAnalogOutput`) - A service to set the analog output `index` to the specified `voltage`.
```suggestion
* `/set_analog_output` (`phidgets_msgs/SetAnalogOutput`) - A service to set the analog output `index` to the specified `voltage`.
```

2021-09-28 14:22 UTC, clalancette commented on phidgets_analog_outputs/src/analog_outputs_ros_i.cpp
> +#include <memory>
This file should have a copyright notice at the top (the fact that it is missing from https://github.com/ros-drivers/phidgets_drivers/blob/noetic/phidgets_digital_outputs/src/digital_outputs_ros_i.cpp is a bug).

2021-09-28 14:22 UTC, clalancette commented on phidgets_api/include/phidgets_api/analog_output.h
> +#include <functional>
This comment is still open.

2021-09-28 14:22 UTC, clalancette commented on phidgets_api/src/analog_outputs.cpp
> +#include <string>
This comment is still open.

2021-09-28 20:21 UTC, clalancette approved these changes
This looks good to me, thanks for iterating!  I'll wait a little while before merging to give @mintar the chance to take a look.

2021-09-29 05:28 UTC, CaPlasberg commented
Thanks for all your hints and feedback!

2021-09-29 08:17 UTC, mintar requested changes

2021-09-29 08:17 UTC, mintar commented on phidgets_api/src/analog_output.cpp
> +    : channel_(channel)
This line should be removed (see above).

2021-09-29 08:17 UTC, mintar commented on phidgets_api/include/phidgets_api/analog_output.h
> +    int channel_;
The member variable `channel_` is used nowhere, so this line should be removed.

2021-09-29 08:17 UTC, mintar commented on phidgets_api/src/analog_output.cpp
> +        throw Phidget22Error("Failed to get analog sensor value", ret);
The error message should be `"Failed to set analog output voltage"`.

2021-09-29 08:17 UTC, mintar commented on phidgets_msgs/CMakeLists.txt
> +    SetAnalogOutput.srv
The list should be sorted, so put `SetAnalog...` before `SetDigital...`.

2021-09-29 08:19 UTC, mintar commented
Thanks for the PR! I've added some comments. Once they are addressed, I'll merge this. Since I'll use "squash and merge", make sure that your name + email address is in your GitHub profile if you want it to show up in the commit message, otherwise GitHub will turn it into something like "CaPlasberg@githubusers.none".

2021-09-29 12:16 UTC, mintar commented
Closing and re-opening to trigger CI tests.

2021-09-29 15:36 UTC, mintar approved these changes

2021-09-29 15:37 UTC, merged

2021-09-29 15:44 UTC, mintar commented
Merged and released!

I guess somebody should port this to ROS2 as well...