Noetic networkhub
ros-drivers/phidgets_drivers pull request #127
Opened 2022-04-05 16:29 UTC by J-C-Haley

Added two parameters, server_name and server_ip, to allow connection to network & wireless VINT hubs to all libraries. Tested only on a temperature phidget, but should work on anything that connects to a vint hub.

2022-04-06 09:30 UTC, mintar commented on phidgets_digital_outputs/launch/digital_outputs.launch
> +    <!-- <param name="server_name" value="myPhidgetServer" /> -->
There's some extra whitespace at the beginning of this line.

2022-04-06 11:09 UTC, mintar requested changes
Apart from the tiny whitespace issue (see my comment above), this looks good to me.

2022-04-06 11:10 UTC, mintar commented
Thanks the PR, and for copy-pasting it everywhere. @clalancette : We should really think about whether we want to create a superclass where we can put all of this stuff so we don't duplicate code everywhere...

2022-04-06 12:19 UTC, clalancette commented
> Thanks the PR, and for copy-pasting it everywhere. @clalancette : We should really think about whether we want to create a superclass where we can put all of this stuff so we don't duplicate code everywhere...

That seems reasonable to me, though I likely won't have time to do it in the near future.  I'll suggest we go ahead with this PR as-is (with whatever changes it needs), and then we can do a separate PR just doing that cleanup.

2022-04-06 13:41 UTC, mintar commented
>  I'll suggest we go ahead with this PR as-is (with whatever changes it needs), and then we can do a separate PR just doing that cleanup.

Yes, I was going to suggest that as well.

2022-04-06 13:52 UTC, closed without merging

2022-04-06 13:54 UTC, mintar commented
I've fixed the small whitespace error and merged the PR in 6734150. Thanks for your contribution!

2022-04-06 21:35 UTC, J-C-Haley commented
Thanks! Hurray for my first PR. My two cents is that the specifics for hardware diversification have to happen on some level, so it's kind of nice having these settings in all the repos individually? Then in a bigger launch file different phidgets can be all set with one argument

2022-04-07 09:37 UTC, mintar commented
It was your first PR? Nice! :)

2022-04-08 21:40 UTC, J-C-Haley commented
Thanks! And actually, I've just discovered setting the server parameters isn't necessary if one uses network discovery:

PhidgetNet_enableServerDiscovery(PHIDGETSERVER_DEVICEREMOTE);

would there be any reason to not have this enabled? I can add it as another launch parameter option, or we could just bake it in?

2022-04-28 13:56 UTC, mintar commented
I'd prefer it as a parameter.