sensor_msgs/Temperature and multi-channel readers
ros-drivers/phidgets_drivers pull request #134
Opened 2022-04-08 22:37 UTC by J-C-Haley

Added a sensor_msgs/Temperature topic, giving published temperatures a timestamp. Prior float64 is preserved for now.

Added channel parameter to phidgets_temperature, allowing for multi-port readers.

2022-04-08 22:40 UTC, J-C-Haley commented on phidgets_temperature/launch/temperature.launch
> +    <param name="data_interval_ms" value="250"/>
4 ms doesn't work on a thermocouple reader, setting to default in readme

2022-04-09 09:08 UTC, mintar commented
Thanks! One of the checks is failing. This is because I added a check yesterday to ensure that the code formatting complies with clang-format. To fix this, follow the [pre-commit Formatting Checks](https://github.com/ros-drivers/phidgets_drivers#pre-commit-formatting-checks) section of the README. If you run `pre-commit run -a`, it should fix the formatting automatically for you. Once you commit that, the check should pass.

2022-04-11 10:45 UTC, mintar requested changes
Thanks again for the PR. I've just reviewed it, and I think we should handle multiple channels the same way that they are handled in the other phidgets (for example, you can use the `digital_output` files as a template, reusing as much code as possible): One `temperature` class per channel, then one `temperatures` class to group all channels.

2025-05-08 16:23 UTC, mintar commented
Closing PR because author stopped responding.

2025-05-08 16:23 UTC, closed without merging

2025-05-15 14:32 UTC, J-C-Haley commented
Apologies, this is fine, I imagine you've moved on.