adding support for analog outputs for ROS2
ros-drivers/phidgets_drivers pull request #145
Opened 2022-05-10 15:01 UTC by AlexisFetet

This is a cleaned #144 PR.
This PR adds support on ROS2 Foxy for analog outputs.
This PR adds a new `auto_enable` parameter to enable outputs on output detection.

2022-05-31 15:22 UTC, clalancette commented
Due to the recent releases and movement, this needs a rebase.  Sorry about that.  Do you mind doing that rebase, then I'll review?  Thanks.

2022-05-31 16:30 UTC, mintar commented
In case you're not familiar with git, here is how to do it in your case:

```bash
git reset --hard origin/rolling
git cherry-pick 0f6d963 3672b53
git push --force-with-lease
```

2022-05-31 18:18 UTC, AlexisFetet commented
Hi,
@clalancette this should be good now.
Thanks for the help @mintar really appreciated.

2022-05-31 20:09 UTC, clalancette requested changes
I've left a bunch of very minor comments.  Once those are resolved, I think this is good to merge.  Thanks for the contribution!

2022-05-31 20:09 UTC, clalancette commented on phidgets_analog_outputs/package.xml
> +  <version>2.1.2</version>
This number needs to match the current release, which on the `rolling` branch would be 2.3.0.

2022-05-31 20:09 UTC, clalancette commented on phidgets_analog_outputs/CHANGELOG.rst
> +* Contributors: Carsten Plasberg
Let's remove this file for now.  We'll automatically generate it when we do a new release with this package in place.

2022-05-31 20:09 UTC, clalancette commented on phidgets_msgs/srv/SetAnalogOutput.srv
> +# Sets the state of a digital output.
```suggestion
# Sets the state of an analog output.
```

2022-05-31 20:09 UTC, clalancette commented on phidgets_api/include/phidgets_api/analog_output.hpp
> +#define PHIDGETS_API_ANALOG_OUTPUT_H
```suggestion
#ifndef PHIDGETS_API_ANALOG_OUTPUT_HPP
#define PHIDGETS_API_ANALOG_OUTPUT_HPP
```

2022-05-31 20:09 UTC, clalancette commented on phidgets_api/include/phidgets_api/analog_output.hpp
> +#endif  // PHIDGETS_API_ANALOG_OUTPUT_H
```suggestion
#endif  // PHIDGETS_API_ANALOG_OUTPUT_HPP
```

2022-05-31 20:09 UTC, clalancette commented on phidgets_api/include/phidgets_api/analog_outputs.hpp
> +#define PHIDGETS_API_ANALOG_OUTPUTS_H
```suggestion
#ifndef PHIDGETS_API_ANALOG_OUTPUTS_HPP
#define PHIDGETS_API_ANALOG_OUTPUTS_HPP
```

2022-05-31 20:09 UTC, clalancette commented on phidgets_api/include/phidgets_api/analog_outputs.hpp
> +#endif  // PHIDGETS_API_ANALOG_INPUTS_H
```suggestion
#endif  // PHIDGETS_API_ANALOG_INPUTS_HPP
```

2022-05-31 20:09 UTC, clalancette commented on phidgets_analog_outputs/src/analog_outputs_ros_i.cpp
> +#include <memory>
```suggestion
#include <functional>
#include <memory>
#include <string>
```

2022-06-01 07:22 UTC, AlexisFetet commented
Hi @clalancette,
I applied the suggested changes, please let me know if anything else need to be changed.

2022-06-01 12:41 UTC, clalancette approved these changes
I noticed one more header guard fix that I missed last review.  I've fixed that myself.

With that, this looks good to me!  Once the CI comes back green, I'll go ahead and merge it.  Thanks for the contribution.

2022-06-01 12:53 UTC, merged