Only publish motor_back_emf if supported by DC Motor device
ros-drivers/phidgets_drivers pull request #53
Opened 2019-09-24 15:13 UTC by peterpolidoro

Only publish motor_back_emf if supported by DC Motor device

2019-09-25 12:22 UTC, clalancette requested changes
Thanks for the contribution!  I have a few things that I think should be changed before this gets in, but they should be relatively easy to fix.

2019-09-25 12:22 UTC, clalancette commented on phidgets_motors/src/motors_ros_i.cpp
> +            if (motors_->backEMFSensingSupported(i))
Honestly, I wouldn't bother with this.  It's somewhat subjective, but I'd rather just unconditionally create the topic.  If the underlying device doesn't support it, then we will never get a callback and never publish anything on it, which is fine.

I think you'll still want to keep the `backEMFSensingSupported` method so you can print an `RCLCPP_INFO` about whether it is supported or not.

2019-09-25 12:22 UTC, clalancette commented on phidgets_api/src/motor.cpp
> +    if (back_emf_sensing_supported_)
I think we should put this code back to how it was, and instead just add at the top:

```
if (!back_emf_sensing_supported_)
{
    throw Phidget22Error("Back EMF not supported", EPHIDGET_UNSUPPORTED);
}
```

2019-09-25 12:22 UTC, clalancette commented on phidgets_api/src/motor.cpp
> +    if (back_emf_sensing_supported_)
This shouldn't be necessary; if back EMF is not supported, then we would have failed to install the change handler during construction.  So I think you can just remove this.

2019-09-25 12:22 UTC, clalancette commented on phidgets_motors/src/motors_ros_i.cpp
> +            if (motors_->backEMFSensingSupported(i))
I think it is better to move this check into `publishLatestBackEMF`; that way, we avoid duplicating the logic.

2019-09-26 13:22 UTC, clalancette commented
I've made a few more changes and made a pull request to this pull request: https://github.com/janelia-ros/phidgets_drivers/pull/1 .  If you agree with those changes, please "Rebase and merge" that PR into this one, and then I'll merge the whole lot into the "dashing" branch.  Thanks!

2019-09-26 14:19 UTC, peterpolidoro commented
Thanks for patiently looking over these changes! Hopefully it will be easier for you to review my future changes as I learn more of your preferred coding styles. I merged, but did not rebase. Is it typical to collapse all pull request changes into a single commit? Would you like me to do that on my end or can you do that as you merge it back into the dashing branch?

2019-09-26 14:39 UTC, clalancette commented
> Thanks for patiently looking over these changes! Hopefully it will be easier for you to review my future changes as I learn more of your preferred coding styles. 

No problem at all.

> I merged, but did not rebase. Is it typical to collapse all pull request changes into a single commit?

It depends on the maintainer and the specific pull request.  In this case, I think we'll want to "Squash and rebase", since it is all one logical change.

> Would you like me to do that on my end or can you do that as you merge it back into the dashing branch?

I'll do it when I merge.  Thanks again for the contribution.

2019-09-26 14:39 UTC, clalancette approved these changes

2019-09-26 14:39 UTC, merged