Use private node handler for params.
ros-drivers/phidgets_drivers pull request #79
Opened 2020-06-20 19:21 UTC by edavies64

I noticed that the high speed encoder library doesn't respect the parameters set in a launch file because they are supposed to private not public. This fix allows tick2rad and the serial number to be properly set for each channel. Also changed the printout for ROS_INFO about channel name to properly output desired information. 
```
[ INFO] [1592680369.498374641]: Channel 0 Name: 'back_left_wheel_joint', Tick2rad: '0.001088' 
```

This has been tested and works on our robot. 
Also, the phidgets wiki reference for parameters are outdated. They still reference 0.7.9 instead of new names in 0.7.10. In particular "serial_name" has been changed to "serial_number"

2020-06-20 19:41 UTC, seebq commented
Hey @mintar I paired with @edavies64 on this fix and can confirm that without this, it doesn't load the correct params with a launch file.

Wonder why the CI didn't build though?

Will there be more renaming and changes to param names? if so, we may keep our fork.

2020-06-22 07:33 UTC, mintar requested changes
Thanks for your PR! Could you please fix the change I suggested and drop me a message, so I can squash + merge? I've also updated the wiki as you suggested; I don't believe `serial_name` was ever correct, it should always have been `serial_number`.

2020-06-22 07:33 UTC, mintar commented on phidgets_high_speed_encoder/src/high_speed_encoder_ros_i.cpp
> +        ROS_INFO("Channel %u Name: '%s', Tick2rad: '%f'", i, joint_names_[i].c_str(), joint_tick2rad_[i]);
```suggestion
        ROS_INFO("Channel %u Name: '%s', Tick2rad: '%f'", i,
                 joint_names_[i].c_str(), joint_tick2rad_[i]);
```

This change should fix [this code style test](https://travis-ci.org/github/ros-drivers/phidgets_drivers/jobs/700421992#L1312-L1316).

2020-06-23 06:22 UTC, mintar commented
@ros-pull-request-builder Retest this please

2020-06-23 07:58 UTC, merged

2020-06-23 08:14 UTC, mintar commented
> Will there be more renaming and changes to param names? if so, we may keep our fork.

No, apart from obvious bug fixes like this one there won't be any changes to parameter names. If I decide to change parameters (for example, renaming `PUBLISH_RATE` to `publish_rate`), I'll follow a tick-tock scheme, that is if the parameter `publish_rate` is not found, I'll look for the parameter `PUBLISH_RATE` instead and print a deprecation warning.

2020-06-23 08:15 UTC, mintar commented
Also note that `serial_name` was never used in the code, and the parameter was not changed. Only the wiki documentation was incorrect.

2020-06-23 13:21 UTC, seebq commented
Understood, thank you!

Feel free to delegate issues/fixes to me @seebq or @edavies64 on this library if needed, we'd like to help.

2020-06-23 15:36 UTC, mintar commented
> Feel free to delegate issues/fixes to me @seebq or @edavies64 on this library if needed, we'd like to help.

Thanks for your offer, I'll remember that!